In [1]:
import pandas as pd

wine = pd.read_csv('http://bit.ly/wine_csv_data')

In [2]:
data = wine[['alcohol', 'sugar', 'pH']]
target = wine[['class']]

In [4]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, target, random_state=42)

In [5]:
sub_input, val_input, sub_target, val_target = train_test_split(train_input, train_target, random_state=42)

In [10]:
print(data.shape, train_input.shape, test_input.shape)
print(sub_input.shape, val_input.shape)

(6497, 3) (4872, 3) (1625, 3)
(4872, 3) (1625, 3)


In [22]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
print(dt.score(sub_input, sub_target))
print(dt.score(val_input, val_target))


0.9973316912972086
0.8516923076923076


In [23]:
from sklearn.model_selection import cross_validate

scores = cross_validate(dt, train_input, train_target)

import numpy as np
np.mean(scores['test_score'])

np.float64(0.8546818301479492)

In [26]:
from sklearn.model_selection import StratifiedKFold

splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_validate(dt, train_input, train_target, cv=splitter)


In [27]:
from sklearn.model_selection import GridSearchCV

In [29]:
params = {
    'min_impurity_decrease': [0.0001, 0.0002, 0.0003, 0.0004, 0.0005]
}

In [31]:
dt = DecisionTreeClassifier(random_state=42)
gs = GridSearchCV(dt, params)

In [32]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [33]:
gs.best_estimator_

DecisionTreeClassifier(min_impurity_decrease=0.0003, random_state=42)

In [35]:
gs.best_params_

{'min_impurity_decrease': 0.0003}

In [36]:
gs.cv_results_

{'mean_fit_time': array([0.01007643, 0.00976906, 0.00438409, 0.0045835 , 0.00418501]),
 'std_fit_time': array([0.00189509, 0.00118966, 0.00048809, 0.00048834, 0.00039873]),
 'mean_score_time': array([0.00480323, 0.00438294, 0.00239305, 0.00199413, 0.00199423]),
 'std_score_time': array([7.52761082e-04, 4.83987522e-04, 4.88188328e-04, 2.61174468e-07,
        2.43140197e-07]),
 'param_min_impurity_decrease': masked_array(data=[0.0001, 0.0002, 0.0003, 0.0004, 0.0005],
              mask=[False, False, False, False, False],
        fill_value=1e+20),
 'params': [{'min_impurity_decrease': 0.0001},
  {'min_impurity_decrease': 0.0002},
  {'min_impurity_decrease': 0.0003},
  {'min_impurity_decrease': 0.0004},
  {'min_impurity_decrease': 0.0005}],
 'split0_test_score': array([0.87384615, 0.87076923, 0.87282051, 0.86461538, 0.86051282]),
 'split1_test_score': array([0.86666667, 0.86871795, 0.87794872, 0.88512821, 0.87794872]),
 'split2_test_score': array([0.88603696, 0.88295688, 0.8798768 , 0.87

In [45]:
import numpy as np

params = {
    'mim_impuriy_decrease': np.arange(0.0001, 0.001, 0.0001),
    'max_depth': range(5, 20, 1),
    'min_sample_split': range(2, 100, 10),
}

In [46]:
dt = DecisionTreeClassifier(random_state=42)

gs = GridSearchCV(dt, params, n_jobs=-1)

In [47]:
gs.fit(train_input, train_target)

ValueError: Invalid parameter 'mim_impuriy_decrease' for estimator DecisionTreeClassifier(max_depth=5, random_state=42). Valid parameters are: ['ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'random_state', 'splitter'].

In [42]:
gs.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [44]:
gs.cv_results_['mean_test_score']s

AttributeError: 'GridSearchCV' object has no attribute 'cv_results_'

In [49]:
from scipy.stats import uniform, randint

In [50]:
randint(0, 10).rvs(10) #randint 균등한 범위 안에 데이터를 만드는 역할?

array([5, 8, 5, 9, 7, 3, 8, 6, 0, 3])

In [52]:
rgen = randint(0, 10)
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([109,  76, 101,  85,  97, 112, 114, 106,  97, 103]))

In [59]:
params = {
    'min_impurity_decrease' :uniform(0.0001, 0.001),
    'max_depth' : randint(20, 50),
    'min_samples_split': randint(2, 25),
    'min_samples_leaf' : randint(1, 25),

    
}

In [60]:
from sklearn.model_selection import RandomizedSearchCV

In [61]:
gs = RandomizedSearchCV(dt, params, n_iter=100, n_jobs=-1)
gs.fit(train_input, train_target)

C:\Users\2-10\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\ma\core.py:2846: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


RandomizedSearchCV(estimator=DecisionTreeClassifier(random_state=42),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000029C29E75FD0>,
                                        'min_impurity_decrease': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x0000029C2B7C8500>,
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000029C29E77320>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x0000029C29E76C00>})

In [62]:
gs.best_estimator_

DecisionTreeClassifier(max_depth=20,
                       min_impurity_decrease=np.float64(0.0005198212394753976),
                       min_samples_leaf=4, min_samples_split=22,
                       random_state=42)

In [63]:
gs.best_params_

{'max_depth': 20,
 'min_impurity_decrease': np.float64(0.0005198212394753976),
 'min_samples_leaf': 4,
 'min_samples_split': 22}